#!/bin/bash
s="$HOME""/Bash/MyFedoraScripts/FedoraScripts"
f="$s""/archive/runall.desktop"

echo 'PATH="$PATH:'"$s"'";export PATH' >> "$HOME""/.bash_profile"

t="$HOME"'/.config/autostart'
mkdir -p "$t"
cp "$f" "$t"

t="$HOME"'/.local/share/applications'
mkdir -p "$t"
cp "$f" "$t"
