#!/bin/bash
s=$HOME/Bash/MyFedoraScripts/FedoraScripts
echo 'PATH="$PATH:'$s'";export PATH' >> $HOME/.bash_profile
cp $s/archive/runall.desktop $HOME/.config/autostart
cp $s/archive/runall.desktop $HOME/.local/share/applications
