#!/bin/bash
function hypotenuse   # Calculate hypotenuse of a right triangle.
{  # c = sqrt( a^2 + b^2 )
  hyp=$(bc -l << EOF
  scale = 24
  sqrt ( $1 * $1 + $2 * $2 )
EOF
  )
# Can't directly return floating point values from a Bash function.
# But, can echo-and-capture:
  echo "$hyp"
}

hyp=$(hypotenuse 3.68 7.31)
echo "hypotenuse = $hyp"    # 8.184039344

function progressbar   # Perform division of two numbers
{  # c = a / b
  progress=$(bc -l << EOF
  scale = 6
  $1 / $2
EOF
  )
# Can't directly return floating point values from a Bash function.
# But, can echo-and-capture:
  echo "$progress"
}

num=0
progress=$(progressbar $num 360)
echo -ne "progress = $progress\r"

num=$(($num + 1))
progress=$(progressbar $num 360)
echo -ne "progress = $progress\r"

num=$(($num + 1))
progress=$(progressbar $num 360)
echo "progress = $progress"
