#!/bin/bash
cat /etc/motd
str=$(stat -c %y /etc/motd)
str=${str::19}
str='Modified: '$str
echo $str
systemctl list-timers dnf-a* --all
grep OnBoot /usr/lib/systemd/system/dnf-automatic.timer
grep OnUnit /usr/lib/systemd/system/dnf-automatic.timer
dnf check -C
dnf repoquery -C --unneeded
