#!/bin/bash
cat /etc/motd
ls -al /etc/motd
systemctl list-timers dnf-a* --all
cat /usr/lib/systemd/system/dnf-automatic.timer | grep OnBoot
cat /usr/lib/systemd/system/dnf-automatic.timer | grep OnUnit
dnf check -C
dnf repoquery -C --unneeded
