#!/bin/python3
from math import sqrt
from plumbum import local, FG, BG
import pyautogui as gui
import sys
import time

gui.PAUSE = 0.02
gui.FAILSAFE = True

gui.keyUp('enter')

wmctrl = local['wmctrl']
wmctrl['-xa', 'geany.Geany'] & FG

time.sleep(0.1)

_next = '.'

if len(sys.argv) == 1:
	sys.argv += [100] * 5
_dip = str(100 - int(sys.argv[1]))
_mar = str(100 - int(sys.argv[2]))
_ste = str(100 - int(sys.argv[3]))
_int = str(100 - int(sys.argv[4]))
_lea = str(100 - int(sys.argv[5]))

_list = ['add_diplomacy ' + _dip]
_list += ['add_martial ' + _mar]
_list += ['add_stewardship ' + _ste]
_list += ['add_intrigue ' + _int]
_list += ['add_learning ' + _lea]
_list += ['add_artifact armor_tier_4_guardian']
_list += ['add_artifact chinese_book_economy']
_list += ['add_artifact chinese_dragon_amulet']
_list += ['add_artifact heros_crown_2']
_list += ['add_artifact jade_dragon']
_list += ['add_artifact jian_sword']
_list += ['add_artifact the_bestiary']
_list += ['add_artifact the_odyssey']
_list += ['add_artifact treatise_on_fishing']
_list += ['add_trait administrator']
_list += ['add_trait adventurer']
_list += ['add_trait architect']
_list += ['add_trait augustus']
_list += ['add_trait born_in_the_purple']
_list += ['add_trait brave']
_list += ['add_trait brilliant_strategist']
_list += ['add_trait celibate']
_list += ['add_trait charitable']
_list += ['add_trait chaste']
_list += ['add_trait content']
_list += ['add_trait crusader_king']
_list += ['add_trait diligent']
_list += ['add_trait duelist']
_list += ['add_trait fair']
_list += ['add_trait falconer']
_list += ['add_trait flanker']
_list += ['add_trait gamer']
_list += ['add_trait gardener']
_list += ['add_trait genius']
_list += ['add_trait gregarious']
_list += ['add_trait groomed']
_list += ['add_trait guilds_trait_master']
_list += ['add_trait honest']
_list += ['add_trait humble']
_list += ['add_trait hunter']
_list += ['add_trait immortal']
_list += ['add_trait inspiring_leader']
_list += ['add_trait just']
_list += ['add_trait kind']
_list += ['add_trait mystic']
_list += ['add_trait organizer']
_list += ['add_trait patient']
_list += ['add_trait physician']
_list += ['add_trait poet']
_list += ['add_trait robust']
_list += ['add_trait scholar']
_list += ['add_trait shrewd']
_list += ['add_trait siege_leader']
_list += ['add_trait socializer']
_list += ['add_trait strategist']
_list += ['add_trait strong']
_list += ['add_trait temperate']
_list += ['add_trait theologian']
_list += ['add_trait trusting']
_list += ['add_trait unyielding_leader']
_list += ['add_trait zealous']
_list += ['add_modifier kuru_ec_bodyguard -1']
_list += ['add_modifier kuru_ec_extraordinary_builder -1']
_list += ['add_modifier kuru_ec_extraordinary_leader -1']
_list += ['add_modifier kuru_ec_extraordinary_plotter -1']
_list += ['add_modifier kuru_ec_quick_reinforcements -1']
_list += ['culture arberian']
_list += ['remove_trait misguided_warrior']
_list += ['remove_trait skilled_tactician']
_list += ['remove_trait tough_soldier']
_list += ['clear']

_iter = iter(_list)

def _check():
	global _next
	_next = next(_iter, 0)
	_bool = _next != 0
	return _bool

while _check():
	gui.write(_next)
	gui.press('enter')
