#!/bin/python3
from math import sqrt
from plumbum import local, FG, BG
import pyautogui as gui
import sys
import time

gui.PAUSE = 0.02
gui.FAILSAFE = True

gui.keyUp('enter')

wmctrl = local['wmctrl']
wmctrl['-xa', 'ck2.ck2'] & FG

time.sleep(0.1)

_next = '.'

_id = sys.argv[1]

_list = ['play ' + _id]
_list += ['run ck2_buffer']
#_list += ['clear']

_iter = iter(_list)

def _check():
	global _next
	_next = next(_iter, 0)
	_bool = _next != 0
	return _bool

while _check():
	gui.write(_next)
	gui.press('enter')
