#!/bin/python3
from math import sqrt
from plumbum import local, FG, BG
import pyautogui as gui
import pyclip as clip
import sys
import time

gui.PAUSE = 0.02
gui.FAILSAFE = True
gui.keyUp('enter')
clip.copy('.')
wmctrl = local['wmctrl']
_next = '.'
_iter = iter(['.'])
_id = sys.argv[1]

_list = ['set_faith messalian ' + _id] #Messalianism
_list += ['clear_traits ' + _id]
_list += ['set_sexuality heterosexual ' + _id]
_list += ['add_trait generous ' + _id]
_list += ['add_trait gregarious ' + _id]
_list += ['add_trait lustful ' + _id]
_list += ['add_trait zealous ' + _id]
_list += ['add_trait adventurer ' + _id]
_list += ['add_trait aggressive_attacker ' + _id]
_list += ['add_trait athletic ' + _id]
_list += ['add_trait augustus ' + _id]
_list += ['add_trait beauty_good_3 ' + _id]
_list += ['add_trait born_in_the_purple ' + _id]
_list += ['add_trait comfort_eater ' + _id]
_list += ['add_trait confider ' + _id]
_list += ['add_trait crusader_king ' + _id]
_list += ['add_trait education_diplomacy_5 ' + _id]
_list += ['add_trait education_intrigue_5 ' + _id]
_list += ['add_trait education_learning_5 ' + _id]
_list += ['add_trait education_martial_5 ' + _id]
_list += ['add_trait education_martial_prowess_4 ' + _id]
_list += ['add_trait education_republican_knowledge_4 ' + _id]
_list += ['add_trait education_stewardship_5 ' + _id]
_list += ['add_trait fecund ' + _id]
_list += ['add_trait flexible_leader ' + _id]
_list += ['add_trait forder ' + _id]
_list += ['add_trait greatest_of_khans ' + _id]
_list += ['add_trait intellect_good_3 ' + _id]
_list += ['add_trait journaller ' + _id]
_list += ['add_trait lifestyle_blademaster ' + _id]
_list += ['add_trait lifestyle_gardener ' + _id]
_list += ['add_trait lifestyle_herbalist ' + _id]
_list += ['add_trait lifestyle_hunter ' + _id]
_list += ['add_trait lifestyle_mystic ' + _id]
_list += ['add_trait lifestyle_physician ' + _id]
_list += ['add_trait lifestyle_reveler ' + _id]
_list += ['add_trait logistician ' + _id]
_list += ['add_trait military_engineer ' + _id]
_list += ['add_trait organizer ' + _id]
_list += ['add_trait physique_good_3 ' + _id]
_list += ['add_trait pilgrim ' + _id]
_list += ['add_trait poet ' + _id]
_list += ['add_trait pure_blooded ' + _id]
_list += ['add_trait shrewd ' + _id]
_list += ['add_trait strong ' + _id]
_list += ['add_trait unyielding_defender ' + _id]
_list += ['set_stress 0 ' + _id]
_list += ['set_diplomacy 100 ' + _id]
_list += ['set_martial 100 ' + _id]
_list += ['set_stewardship 100 ' + _id]
_list += ['set_intrigue 100 ' + _id]
_list += ['set_learning 100 ' + _id]
_list += ['set_prowess 100 ' + _id]
_list += ['set_dread 100 ' + _id]
_list += ['effect create_artifact_reichskrone_effect = { OWNER = this }']
_list += ['effect create_artifact_illustrious_sassanian_sword_effect = { OWNER = this }']
_list += ['effect create_artifact_navaratna_effect = { OWNER = this }']
_list += ['effect create_artifact_navaratna_effect = { OWNER = this }']
_list += ['effect create_artifact_navaratna_effect = { OWNER = this }']
_list += ['effect create_artifact_navaratna_effect = { OWNER = this }']
_list += ['effect create_artifact_turquoise_throne_effect = { OWNER = this }']
_list += ['effect create_artifact_dhammapada_effect = { OWNER = this }']
_list += ['effect create_artifact_dhammapada_effect = { OWNER = this }']
_list += ['effect create_artifact_sculpture_ark_of_covenant_effect = { OWNER = this }']
_list += ['effect create_artifact_sculpture_ark_of_covenant_effect = { OWNER = this }']
_list += ['effect create_artifact_sculpture_ark_of_covenant_effect = { OWNER = this }']
_list += ['effect create_artifact_kaves_apron_effect = { OWNER = this }']
_list += ['effect create_artifact_kaves_apron_effect = { OWNER = this }']
_list += ['effect create_artifact_kaves_apron_effect = { OWNER = this }']
_list += ['effect create_artifact_pedestal_crown_iron_effect = { OWNER = this }']
_list += ['effect create_artifact_pedestal_crown_iron_effect = { OWNER = this }']
_list += ['effect create_artifact_pedestal_crown_iron_effect = { OWNER = this }']
_list += ['effect create_artifact_pedestal_crown_iron_effect = { OWNER = this }']
_list += ['effect = { every_vassal_or_below  = { set_character_faith = root.faith }}']
_list += ['effect = { every_courtier_or_guest  = { set_character_faith = root.faith }}']
_list += ['effect = { every_vassal_or_below  = { set_culture = root.culture }}']
_list += ['effect = { every_courtier_or_guest = { set_culture = root.culture }}']
_list += ['effect = { every_sub_realm_county = { set_county_faith = root.faith }}']
_list += ['effect = { every_sub_realm_county = { set_county_culture = root.culture }}']
_list += ['clear']

def _check():
	global _next
	_next = next(_iter, 0)
	_bool = _next != 0
	return _bool

def _do():
	global _iter
	wmctrl['-xa', 'ck3.ck3'] & FG
	time.sleep(0.1)
	_iter = iter(_list)
	while _check():
		_loop()

def _loop():
	clip.copy(_next)
	time.sleep(0.05)
	gui.hotkey('ctrl', 'v')
	gui.press('enter')

if __name__ == "__main__":
	_do()

"""
_list += [' ' + _id]
effect create_artifact_reichskrone_effect = { OWNER = this }			x1 Crown			Reichskrone
effect create_artifact_illustrious_sassanian_sword_effect = { OWNER = this }	x1 Regalia			Sassanian Sword
effect create_artifact_navaratna_effect = { OWNER = this }			x4 Trinket			Navaratna
effect create_artifact_turquoise_throne_effect = { OWNER = this }		x1 Throne			Turquoise Throne
effect create_artifact_dhammapada_effect = { OWNER = this }			x2 Book				Dhammapada
effect create_artifact_sculpture_ark_of_covenant_effect = { OWNER = this }	x3 Furniture			Ark of the Covenant
effect create_artifact_kaves_apron_effect = { OWNER = this }			x3 Large Wall Ornament		Kave's Apron
effect create_artifact_pedestal_crown_iron_effect = { OWNER = this }		x4 Pedestal Item		Iron Crown of Lombardy
effect = { every_vassal_or_below  = { set_character_faith = root.faith }}
effect = { every_courtier_or_guest  = { set_character_faith = root.faith }}
effect = { every_vassal_or_below  = { set_culture = root.culture }}
effect = { every_courtier_or_guest = { set_culture = root.culture }}
effect = { every_sub_realm_county = { set_county_faith = root.faith }}
effect = { every_sub_realm_county = { set_county_culture = root.culture }}
"""
