#!/bin/bash
eval "$(xdotool getmouselocation --shell)"
X2=$((X+104))
xdotool keyup Return
wmctrl -a "$1"
sleep 0.3
for((i=0;i<"$2";i++))
do
  xdotool mousemove --sync "$X" "$Y" click 1 sleep 0.008
  xdotool mousemove --sync "$X2" "$Y" click 1 sleep 0.008
done
