#!/bin/python3
from plumbum import local
from plumbum import FG, BG
import pyautogui as gui
import sys
import time

gui.PAUSE = 0.02
gui.FAILSAFE = True

gui.keyUp('enter')

wmctrl = local["wmctrl"]
wmctrl["-xa", sys.argv[1]] & FG

time.sleep(0.1)

_x, _y = gui.position()

t_len = eval(sys.argv[2])
t_len = float(t_len)
t_len = round(t_len, 9)
t_end = time.monotonic() + t_len

while time.monotonic() < t_end:
	gui.click(x=_x, y=_y)
