#!/bin/python3
import pyautogui as gui
import subprocess
import sys
import time

gui.PAUSE = 0.02
gui.FAILSAFE = True

x, y = gui.position()

n=int(sys.argv[1])
for i in range(n):
	gui.click(x=x, y=y)
