#!/bin/bash
source yesno

function closeandreboot {
	closeall
	sudo dnf system-upgrade reboot
}

sudo dnf -y system-upgrade download --refresh --allowerasing --releasever=$1
if confirm
then
	closeandreboot &
fi
