#!/bin/bash
source yesno
v="$(rpm -E %fedora)"
v="$((v+1))"

function close_and_dnf_reboot
{
	closeall
	wait
	sudo -A dnf system-upgrade reboot
}

sudo -A dnf -y system-upgrade download --refresh --allowerasing --releasever="$v"
if confirm 'Reboot to perform system upgrade now[Y/n]? '
then
	close_and_dnf_reboot &
fi
