#!/bin/bash
file=$HOME/Bash/MyFedoraScripts/FedoraScripts/progs
echo '#!/bin/bash' > $file
data='sudo dnf -y install '
que=$(dnf repoquery --userinstalled --queryformat '%{name}')
echo $data$que >> $file
