#!/bin/bash
sleep 1
wmctrl -a "Bos Wars"
for((i=0;i<$1;i++))
do
#	echo 'gimme unit-jet '$2 > $HOME/typestr
#	xclip -i $HOME/typestr -selection clipboard
	xdotool key Return
	sleep 0.2
#	xdotool key Ctrl+v
	xdotool type 'gimme unit-jet '$2
	sleep 0.02
	xdotool key Return
done
