#!/bin/bash
xdotool key --clearmodifiers Alt+Tab
sleep 1
for((i=0;i<$1;i++))
do
	sleep $2
	xdotool type gimme
	sleep $2
	xdotool key space
	sleep $2
	xdotool type unit-cannon
	sleep $2
	xdotool key space
	sleep $2
	xdotool type $3
	sleep $2
	xdotool key Return
done
