#!/bin/bash
sudo -A update-alternatives --config 'java'
sudo -A update-alternatives --config 'javac'
sudo -A update-alternatives --config 'jre_openjdk'
sudo -A update-alternatives --config 'java_sdk_openjdk'
update-alternatives --list | grep 'jvm'
