#!/bin/bash
source trycatch
sleep 0.5
sleep 10 &
x=$(pidof -s sleep)
kill -TSTP $x &
for((i=0;i<$1;i++))
do
	sleep 0.2
	xdotool mousemove --sync 120 173 click 1
	sleep 0.2
	xdotool mousemove --sync 168 173 click 1
	sleep 0.2
	xdotool mousemove --sync 440 440 click 1
	sleep 0.2
	xdotool mousemove --sync 460 460 click 1
	try
	(
		echo "try"
	)
	catch || {
		echo "catch"
	}
done
kill -CONT $x &
