#!/bin/bash
source trycatch
sleep 0.5
xdotool key --clearmodifiers Alt+Tab
sleep 1.0
sleep 10 &
kill -TSTP $(pidof sleep)
for((i=0;i<$1;i++))
do
	sleep 0.2
	xdotool mousemove --sync 120 173 click 1
	sleep 0.2
	xdotool mousemove --sync 168 173 click 1
	sleep 0.2
	xdotool mousemove --sync 440 440 click 1
	sleep 0.2
	xdotool mousemove --sync 460 460 click 1
	sleep 0.2
	xdotool key p
	sleep 0.2
	xdotool key a
	try
	(
		echo "try"
	)
	catch || {
		echo "catch"
	}
done
kill -CONT $(pidof sleep)
