#!/bin/bash
s=''
function luu
{
  d="/run/media/${USER}/18327 MiB/${s}"
  if [[ ! -d "${d}" ]]
  then
    sudo -A mkdir -p "${d}"
    cd "${d}/.."
    sudo -A git clone "https://github.com/mattiasmun/${s}.git"
  fi
  cd "${d}"
  sudo -A git pull --rebase
}

s='MyFedoraScripts'
luu
s='noscriptsettings'
luu
