#!/bin/bash
# choose 'choice 1' 'choice 2' ...
#  Prints menu to standard error. Prompts with PS3.
#  Reads REPLY from standard input. Sets CHOICE.
s00='fee fie'
s01='huff and puff'
s02='mirror mirror'
s03='tick tock'
s04='exit'

function choose
{
  CHOICE=            # Default CHOICE is empty string.
  [[ $# -gt 0 ]] || return  # Return if "$@" is empty.
  select CHOICE        # Select from "$@".
  do
    case "$CHOICE" in
    "$s00" | "$s01" | "$s02" | "$s03")
      break
      ;;
    "$s04")
      exit
      ;;
    *)
      echo Invalid choice.
      ;;
    esac
  done
}

function list
{
  PS3='Which is from the three pigs: '
  choose "$s00" "$s01" "$s02" "$s03" "$s04"
  if [[ -n $CHOICE ]]
  then
    echo You chose: "$CHOICE".
  fi
}

while true
do
  list
  echo -----------------------------------
done
