#!/bin/bash
# choose 'choice 1' 'choice 2' ...
#	Prints menu to standard error. Prompts with PS3.
#	Reads REPLY from standard input. Sets CHOICE.
function choose {
	CHOICE=						# Default CHOICE is empty string.
	[[ $# -gt 0 ]] || return	# Return if "$@" is empty.
	select CHOICE				# Select from "$@".
	do
		case $CHOICE in
		'fee fie' | 'huff and puff' | 'mirror mirror' | 'tick tock')
			break
			;;
		'exit')
			exit
			;;
		*)
			echo Invalid choice.
			;;
		esac
	done
}

function list {
	PS3='Which is from the three pigs: '
	choose 'fee fie' 'huff and puff' 'mirror mirror' 'tick tock' 'exit'
	if [[ -n $CHOICE ]]
	then
		echo You chose: ${CHOICE}.
	fi
}

while true
do
	list
	echo -----------------------------------
done
