#!/bin/python3
0 Stora Malbro flygplats 77x15
1 Ängelhammar flygplats 83x46
2 Nya Grörtsala helikopterplats 116x64
3 Titskrona flygplats 77x76
4 Östra Ängelhammar 49x48
5 Gamla Erikslätt flygplats 12x67
6 Sprippkulle flygplats 12x89
7 Drotbyn flygplats 89x166
8 Gnylvalla flygplats 92x204
9 Tratthammar flygplats 100x251
10 Sandudde flygplats 61x227
11 Krånnbukten flygplats 41x203
12 Nävköping flygplats 17x234
13 Oskarberg flygplats 20x193

from tsp_solver.greedy_numpy import solve_tsp
import tsp_solver.demo.tsp

lx,ly = [77,83,116,77,49,12,12,89,92,100,61,41,17,20],[15,46,64,76,48,67,89,166,204,251,227,203,234,193]
endps=(5,6)
matrix = tsp_solver.demo.tsp.make_dist_matrix(lx,ly)
path = solve_tsp(matrix, endpoints = endps)
print(path)

[5, 4, 0, 1, 3, 2, 7, 8, 9, 10, 12, 13, 11, 6]

Gamla Erikslätt flygplats
Östra Ängelhammar
Stora Malbro flygplats
Ängelhammar flygplats
Titskrona flygplats
Nya Grörtsala helikopterplats
Drotbyn flygplats
Gnylvalla flygplats
Tratthammar flygplats
Sandudde flygplats
Nävköping flygplats
Oskarberg flygplats
Krånnbukten flygplats
Sprippkulle flygplats
