#!/bin/bash
sudo update-alternatives --config java
sudo update-alternatives --config javac
sudo update-alternatives --config jre_openjdk
sudo update-alternatives --config java_sdk_openjdk
update-alternatives --list | grep 'jvm'

cd "${0:0: -11}"
sudo cp 'archive/fstrimz' '/usr/sbin/'
sudo chown root:root '/usr/sbin/fstrimz'
sudo nano '/etc/dnf/automatic.conf'
sudo systemctl edit 'fstrim.service'
sudo systemctl enable --now 'dnf-automatic.timer' 'fstrim.timer'
systemctl daemon-reload
systemctl list-timers --all

cp '/etc/sudo.conf' .
s='Path askpass /usr/libexec/openssh/gnome-ssh-askpass'
echo "$s" >> 'sudo.conf'
chmod 0644 'sudo.conf'
sudo chown root:root 'sudo.conf'
sudo mv 'sudo.conf' '/etc/sudo.conf'
