#!/bin/bash
cd "$HOME/Bash/MyFedoraScripts/FedoraScripts/"

cp archive/.bash_history "$HOME/.bash_history"

./javacfg

./timercfg

alias pip-upgrade="pip freeze --user | cut -d'=' -f1 | xargs -n1 pip install -U"

pip install 'PyAutoGUI' 'tsp-solver2' 'pip-date'

mkdir -p "$HOME/Projects"
cd "$HOME/Projects"
git clone "https://git.sr.ht/~geb/dotool"
cd dotool
make
sudo -A make install
sudo -A usermod -a -G input "$USER"
mkdir -p "$HOME/.config/systemd/user/"
cp "$HOME/Bash/MyFedoraScripts/FedoraScripts/archive/dotool.service" "$HOME/.config/systemd/user/"
systemctl --user enable --now dotool.service

#Network DNS 8.26.56.26, 8.20.247.20
