#!/bin/bash
sudo dnf -y install 0ad VirtualBox adobe-source-code-pro-fonts alternatives \
anaconda anaconda-install-env-deps audacity blivet-gui boswars bsd-games clamav \
ctags dbus-broker dconf-editor deja-dup dkms dnf-automatic dracut-live \
dracut-squash espeak f30-backgrounds-base f30-backgrounds-gnome \
fedora-obsolete-packages fedora-release-common ffmpeg ffmpeg-libs firefox fstrm \
gameconqueror gbrainy gcr-base gimp git gnome-power-manager gnome-screensaver \
gnome-sudoku gnome-tweaks google-chrome-stable gparted gpaste-ui gshutdown \
gstreamer-ffmpeg gstreamer-plugins-bad-free gstreamer-plugins-espeak \
gstreamer-plugins-ugly gtk2-immodule-xim gtk3-immodule-xim gtranslator guile22 \
hardinfo htop hunspell-sv intel-gmmlib intel-media-driver intltool \
java-11-openjdk-devel jitterentropy kmod-VirtualBox-5.1.19-300.fc30.x86_64 \
kmod-VirtualBox-5.1.20-300.fc30.x86_64 kmod-VirtualBox-5.2.7-200.fc30.x86_64 \
kmod-nvidia kmod-nvidia-5.1.19-300.fc30.x86_64 \
kmod-nvidia-5.1.20-300.fc30.x86_64 kmod-nvidia-5.2.7-200.fc30.x86_64 ksirk \
langpacks-en langpacks-sv libhandy libopusenc libpmem libreoffice-help-sv \
libreoffice-langpack-sv libselinux-devel libsepol-devel libvala livecd-tools \
mariadb-connector-c mariadb-connector-c-config meld memtest86+ metacity \
mkpasswd opencc opus-tools opusfile p7zip p7zip-plugins pbzip2 pcre2-devel \
pcre2-utf32 perl-File-Path-Tiny plymouth-theme-spinner python3-IPy \
python3-dnf-plugin-system-upgrade python3-gmpy2 python3-sh pyxtrlock qshutdown \
readline-devel redeclipse redshift-gtk rpmfusion-free-release \
rpmfusion-nonfree-release rpmsphere-release samba-libs smc-anjalioldlipi-fonts \
smc-dyuthi-fonts smc-rachana-fonts smc-raghumalayalamsans-fonts \
smc-suruma-fonts source-highlight spin-kickstarts subversion syslinux \
systemd-rpm-macros translate-shell translate-toolkit vala vlc wesnoth whois-nls \
wmctrl xclip xdotool xforms xlockmore-gtk xz-lzma-compat youtube-dl
