#!/bin/bash
xdotool keyup Return
wmctrl -a "$1"
x="$((2**15*RANDOM+RANDOM))"
v="${HOME}/Video/screenrec${x}.mp4"
ffmpeg -f x11grab -video_size 2560x1440 -framerate 60 -i "${DISPLAY}" -f alsa -i default -c:v hevc_nvenc -preset medium -c:a aac "${v}"
