#!/bin/bash
d=$HOME/.redeclipse
mkdir -p $d
f1=$d/autoexec.cfg
f2=$d/vars.cfg

> $f1

function tof1
{
	echo $1 >> $f1
}

tof1 'bothurtstop 1'
tof1 'botoffset 20'
tof1 'botskillmax 40'
tof1 'botskillmin 40'
tof1 'botspawndelay 60000'
tof1 'botspawndelaydefend 60000'
tof1 'botspeed 30'
tof1 'dronemaxcarry 1'
tof1 'dronespeed 30'
tof1 'gruntmaxcarry 1'
tof1 'gruntspeed 30'
tof1 'jumpspeed 150.0'
tof1 'plasmadisabled 1'
tof1 'playerhealth 99999999'
tof1 'playerhurtstop 1'
tof1 'playermaxcarry 7'
tof1 'playerweight 35.0'
tof1 'turrethurtstop 1'
tof1 'turretmaxcarry 1'
tof1 'zapperdisabled 1'

cp $f1 $f2
