#!/bin/bash
wmctrl -a "Transifex Editor"
for((i=0;i<$1;i++))
do
	sleep 4
	xdotool mousemove --sync 2530 371 click 1
	sleep 0.1
	xdotool mousemove --sync 1275 618 click 1
	sleep 0.1
	xdotool key --clearmodifiers Ctrl+Home
	xdotool key Delete
	xdotool key Delete
	sleep 0.1
	xdotool key Tab
done
