#!/bin/bash
sleep 0.5
#wmctrl -a "0 A.D."

arr=('a')

function a
{
	xdotool key t
	sleep 0.1
}

function b
{
	sleep 0.9
	xdotool key Return
}

function type
{
#	a
	length=${#arr[@]}
#	xdotool type --delay 30 'brainiac '${arr[0]}
#	for((i=1;i<length;i++))
#	do
#		xdotool key underscore
#		xdotool type --delay 30 ${arr[i]}
#	done
#	b
}

function type1
{
	a
	xdotool type --delay 30 'back to the future'
	b
}

function type2
{
	a
	xdotool type --delay 30 'TARDIS'
	b
}

function type3
{
	a
	xdotool type --delay 30 'the hive master'
	b
}

function type4
{
	a
	xdotool type --delay 30 'jame jam'
	b
}

function type5
{
	a
	xdotool type --delay 30 'i am too busy'
	b
}

type1
type1
type2
type3
type4
type5
arr=('armor' 'cav' '01')
type
type 'armor_cav_02'
type 'armor_cav_chamfron'
type 'armor_hero_01'
type 'armor_infantry_01'
type 'armor_infantry_02'
type 'armor_infantry_hack_01'
type 'armor_infantry_hack_02'
type 'armor_infantry_hack_03'
type 'armor_infantry_hack_04'
type 'armor_infantryspearmen_pierce_01'
type 'armor_infantryspearmen_pierce_02'
type 'armor_infantryspearmen_pierce_03'
type 'armor_infantryspearmen_pierce_04'
type 'armor_ship_hullsheathing'
type 'armor_ship_hypozomata'
type 'armor_ship_reinforcedhull'
type 'attack_cav_lance'
type 'attack_cavalry_melee_01'
type 'attack_cavalry_melee_02'
type 'attack_cavalry_ranged_01'
type 'attack_cavalry_ranged_02'
type 'attack_champions_elite'
type 'attack_infantry_melee_01'
type 'attack_infantry_melee_02'
type 'attack_infantry_ranged_01'
type 'attack_infantry_ranged_02'
type 'attack_soldiers_will'
type 'attack_steel_working'
type 'gather_animals_stockbreeding'
type 'gather_capacity_basket'
type 'gather_capacity_carts'
type 'gather_capacity_fishing'
type 'gather_capacity_wheelbarrow'
type 'gather_farming_fertilizer'
type 'gather_farming_plows'
type 'gather_farming_training'
type 'gather_fishing_net'
type 'gather_lumbering_ironaxes'
type 'gather_lumbering_sharpaxes'
type 'gather_lumbering_strongeraxes'
type 'gather_mining_serfs'
type 'gather_mining_servants'
type 'gather_mining_shaftmining'
type 'gather_mining_silvermining'
type 'gather_mining_slaves'
type 'gather_mining_wedgemallet'
type 'gather_wicker_baskets'
type 'heal_barracks'
type 'heal_range'
type 'heal_range_2'
type 'heal_rate'
type 'heal_rate_2'
type 'heal_temple'
type 'health_females_01'
type 'health_regen_units'
type 'health_walls_geometric_masonry'
type 'melee_inf_sidearms'
type 'melee_inf_spearheads'
type 'pop_civic_01'
type 'pop_civic_02'
type 'pop_house_01'
type 'pop_house_02'
type 'pop_wonder'
type 'ranged_inf_irregulars'
type 'ranged_inf_skirmishers'
type 'siege_armor'
type 'siege_attack'
type 'siege_bolt_accuracy'
type 'siege_cost_metal'
type 'siege_cost_wood'
type 'siege_packing'
type 'speed_cavalry_01'
type 'speed_cavalry_02'
type 'spy_counter'
type 'tower_armour'
type 'tower_crenellations'
type 'tower_decay'
type 'tower_murderholes'
type 'tower_range'
type 'tower_vision'
type 'tower_watch'
type 'trade_commercial_treaty'
type 'trade_convoys_armor'
type 'trade_convoys_speed'
type 'trade_gain_01'
type 'trade_gain_02'
type 'training_conscription'
type 'training_naval_architects'
type 'unlock_champion_units'
type 'unlock_females_house'
type 'unlock_shared_dropsites'
type 'unlock_shared_los'
type 'unlock_spies'
type 'upgrade_rank_advanced_cavalry'
type 'upgrade_rank_advanced_infantry'
type 'upgrade_rank_advanced_mercenary'
type 'upgrade_rank_elite_cavalry'
type 'upgrade_rank_elite_infantry'
type 'cost_celt_mercs'
type 'cost_celt_mercs_2'
type 'cost_iberian_mercs'
type 'cost_iberian_mercs_2'
type 'cost_italian_mercs'
type 'cost_italian_mercs_2'
type 'special_colonisation'
type 'special_exploration'
type 'training_phoenician_naval_architects'
type 'traintime_celt_mercs'
type 'traintime_celt_mercs_2'
type 'traintime_iberian_mercs'
type 'traintime_iberian_mercs_2'
type 'traintime_italian_mercs'
type 'traintime_italian_mercs_2'
type 'upgrade_rank_advanced_celts'
type 'upgrade_rank_advanced_iberian'
type 'upgrade_rank_advanced_italiote'
type 'upgrade_rank_elite_celts'
type 'upgrade_rank_elite_iberian'
type 'upgrade_rank_elite_italiote'
type 'special_hellenistic_metropolis'
type 'special_parade_of_daphne'
type 'special_war_horses'
type 'unlock_reform_army'
type 'unlock_traditional_army'
type 'upgrade_mace_silvershields'
type 'attack_inf_spearfighting'
type 'spartans_agoge'
type 'special_iphicratean_reforms'
type 'special_long_walls'
type 'monumental_architecture'
type 'upgrade_rank_elite_healer'
type 'persian_architecture'
type 'special_equine_transports'
type 'training_conscription_cavalry'
type 'training_conscription_infantry'
type 'decay_logistics'
type 'vision_sibylline'
