#!/bin/bash
sleep 0.1
gnome-terminal &
sleep 0.1
thunderbird &
sleep 0.1
firefox &
sleep 0.1
gedit ~/Dokument/Anteckningar &
sleep 0.1
gnome-calculator &
sleep 0.1
nautilus &
sleep 0.1
easyeffects &
sleep 3.3
echo key k:125 | dotool
#dotool key super

#dotoold &
pip3update &
sleep 10
#wmctrl -xa gnome-terminal-server.Gnome-terminal
flatpak update -y
sleep 0.1
flatpak uninstall --unused -y

