#!/bin/bash
sleep 0.1
gnome-terminal &
sleep 0.1
thunderbird &
sleep 0.1
firefox &
sleep 0.1
gedit ~/Dokument/Anteckningar &
sleep 0.1
gnome-calculator &
sleep 0.1
nautilus &
sleep 0.1
easyeffects &
sleep 0.1
pip3update &

sleep 12
wmctrl -xa gnome-terminal-server.Gnome-terminal
flatpak update -y
sleep 0.1
flatpak uninstall --unused -y
sleep 0.1
