#!/bin/bash
sleep 0.1
ptyxis &
sleep 0.1
thunderbird &
sleep 0.1
firefox &
sleep 0.1
gedit ~/Dokument/Anteckningar &
sleep 0.1
gnome-calculator &
sleep 0.1
nautilus &
sleep 0.1
easyeffects &
sleep 3.3
echo key k:125 | dotool

uv self update
uv tool upgrade --all &

flatpak update -y
sleep 0.1
flatpak uninstall --unused -y

