#!/bin/bash
wmctrl -a "0 A.D."
for((i=0;i<$1;i++))
do
	xdotool key Return
	sleep 1
	xdotool type salad
	xdotool key space
	xdotool type bowl
	xdotool key space
	xdotool type $2
	xdotool key Return
done
