#!/bin/bash
s='sudo.conf'
if [[ -e '/etc/'"$s"]]
then
  cp '/etc/'"$s" .
fi

t='Path askpass /usr/libexec/openssh/gnome-ssh-askpass'
echo "$t" >> "$s"

chmod 0644 "$s"
sudo -A chown root:root "$s"
sudo -A mv "$s" '/etc/'"$s"
