#!/bin/python3
from math import sqrt
from plumbum import local, FG, BG
import pyautogui as gui
import pyclip as clip
import sys
import time

gui.PAUSE = 0.02
gui.FAILSAFE = True

gui.keyUp('enter')

wmctrl = local['wmctrl']
wmctrl['-xa', 'geany.Geany'] & FG

time.sleep(0.1)

clip.copy(' ')

time.sleep(0.1)

_next = '.'

_id = sys.argv[1]
if len(sys.argv) == 2:
	sys.argv += [100] * 5
_dip = str(100 - int(sys.argv[2]))
_mar = str(100 - int(sys.argv[3]))
_ste = str(100 - int(sys.argv[4]))
_int = str(100 - int(sys.argv[5]))
_lea = str(100 - int(sys.argv[6]))

_list = ['text one']
_list += ['text two']
_list += ['text three']

_iter = iter(_list)

def _check():
	global _next
	_next = next(_iter, 0)
	_bool = _next != 0
	return _bool

while _check():
	clip.copy(_next)
	try:
		clip.waitForNewPaste(0.02)
	except:
		time.sleep(0.001)
	clip.paste()
	gui.write(_next)
	gui.press('enter')
