#!/bin/python3
from math import sqrt
from plumbum import local, FG, BG
import pyautogui as gui
import pyclip as clip
import sys
import time

gui.PAUSE = 0.02
gui.FAILSAFE = True
gui.keyUp('enter')
clip.copy(' ')
wmctrl = local['wmctrl']
_next = '.'
_iter = iter(['.'])

_list = ['text one']
_list += ['text two']
_list += ['text three']

def _check():
	global _next
	_next = next(_iter, 0)
	_bool = _next != 0
	return _bool

def _do():
	global _iter
	wmctrl['-xa', 'geany.Geany'] & FG
	time.sleep(0.1)
	_iter = iter(_list)
	while _check():
		_loop()

def _loop():
	clip.copy(_next)
#	try:
#		clip.waitForNewPaste(2)
#	except:
#		print("Unexpected error:", sys.exc_info())
#		time.sleep(0.01)
	time.sleep(0.01)
	cb_data = clip.paste()
	print(cb_data)
#	gui.write(_next)
	gui.press('enter')


if __name__ == "__main__":
	_do()
