#!/bin/bash
v="$(rpm -E %fedora)"
sudo dnf -y install 'git' \
  'https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-'"$v"'.noarch.rpm' \
  'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-'"$v"'.noarch.rpm'

sudo dnf -y upgrade

cd "${0:0: -9}"

./getgitrepos

./bashprofileandautostart

./progs

sudo dnf -y groupupdate 'core' 'multimedia' 'sound-and-video' \
  'workstation-product-environment'
  
pip install 'PyAutoGUI' 'tsp-solver2'
