#!/bin/bash
v="$(rpm -E %fedora)"
sudo -A dnf -y install 'git' \
  'https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-'"$v"'.noarch.rpm' \
  'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-'"$v"'.noarch.rpm'

sudo -A dnf -y upgrade

cd "${0:0: -9}"

./getgitrepos

./bashprofileandautostart

./progs

sudo -A dnf -y groupupdate 'core' 'multimedia' 'sound-and-video' \
  'workstation-product-environment'
  
pip install 'PyAutoGUI' 'tsp-solver2' 'pip-date'

#Network DNS 8.26.56.26, 8.20.247.20
