#!/bin/python3
from math import sqrt
from plumbum import local, FG, BG
import pyautogui as gui
import sys
import time

gui.PAUSE = 0.02
gui.FAILSAFE = True
gui.keyUp('enter')
wmctrl = local['wmctrl']
xdotool = local['xdotool']

_x0, _y0 = (0, 0)
_x, _y = (_x0, _y0)
_max_dist = 6
#_pix = (0, 0)
_name = 'TransportFever2.TransportFever2'
_t_len = eval(sys.argv[1])
_t_len = float(max(_t_len, 1))
_t_end = 0
_interval = eval(sys.argv[2])
_interval = float(_interval)

def _check():
	_x, _y = gui.position()
	_d_x = _x0 - _x
	_d_y = _y0 - _y
	_dist = sqrt(_d_x * _d_x + _d_y * _d_y)
	_bool = _dist <= _max_dist
	_bool = time.monotonic() < _t_end and _bool
#	_bool = gui.pixelMatchesColor(_x0, _y0, _pix, tolerance=8) and _bool
	return _bool

def _do():
	global _x0, _y0, _t_end
	_x0, _y0 = gui.position()
#	_pix = gui.pixel(_x0, _y0)
	wmctrl['-xa', _name] & FG
	xdotool['keydown', 'ISO_Level3_Shift'] & FG
	time.sleep(0.1)
	_t_end = time.monotonic() + _t_len
	while _check():
#		gui.keyDown('altright')
		gui.press('m', presses = 5, interval = _interval)
#		gui.keyUp('altright')
	xdotool['keyup', 'ISO_Level3_Shift'] & FG

if __name__ == "__main__":
	_do()
