#!/bin/bash
xdotool keyup Return
wmctrl -a 'Transifex Editor'
sleep 0.3
for((i=0;i<$1;i++))
do
	sleep 0.1
	xdotool mousemove --sync 1214 301 click --repeat 3 1
	specialcopy
	xdotool mousemove --sync 1275 618 click --repeat 3 1
	sleep 0.1
	xdotool key --clearmodifiers Ctrl+v
	sleep 0.1
	xdotool key Delete
	sleep 0.1
	xdotool key Tab
	sleep 4
done
