#!/bin/bash
wmctrl -a "0 A.D. | Transifex Editor"
sleep 1
for((i=0;i<$1;i++))
do
	sleep 0.1
	xdotool mousemove --sync 1213 301 click 1
	sleep 0.1
	xdotool key --clearmodifiers Ctrl+a
	specialcopy
	xdotool mousemove --sync 1275 618 click 1
	sleep 0.1
	xdotool key --clearmodifiers Ctrl+a
	sleep 0.1
	xdotool key --clearmodifiers Ctrl+v
	sleep 0.1
	xdotool key Tab
	sleep 4
done
