#!/bin/bash
xdotool key --clearmodifiers Alt+Tab
sleep 1.0
for((i=0;i<$1;i++))
do
	sleep  0.26
	xdotool key Up
	sleep  0.26
	xdotool key Down
	sleep  0.26
	xdotool key Up
	sleep  0.26
	xdotool key Down
	sleep  0.26
	xdotool key Up
	sleep  0.26
	xdotool key Down
	sleep  0.26
	xdotool key Up
	sleep  0.26
	xdotool key Down
	sleep  0.26
	xdotool key Up
	sleep  0.26
	xdotool key Down
	sleep  0.26
	xdotool key Up
done
