#!/bin/bash
wmctrl -a firefox
sleep 1.0

function upgrade()
{
	for((j=0;j<34;j++))
	do
		sleep 0.1
		xdotool mousemove --sync 597 519 click 1
	done
}

function iterate()
{
	x=$1+32*$3+1
	for((i=$1;i<$x;i+=32))
	do
		sleep 0.1
		xdotool mousemove --sync $2 $i click 1
		upgrade
	done
}

#iterate 220 84 14
#iterate 254 500 14
iterate 149 255 10
