#!/bin/bash
eval $(xdotool getmouselocation --shell)
xdotool keyup Return
wmctrl -a "$1"
sleep 0.3
a=$2
a0=5
a1=0
a2=292
a3=83
for((i=0;a>0;i++))
do
	a1=$a0
	if (( $a < $a0 ))
	then
		a1=$a
	fi
	for((j=0;j<$a1;j++))
	do
		xdotool mousemove --sync $X $((Y+j*a2)) click 1
		sleep 0.3
	done
	xdotool key Next
	a=$((a-a0))
	test $a -gt 0 && sleep $((a0*7/5))
	if (( $Y < 226 ))
	then
		test $a0 = 4 && Y=$((Y+a2))
		Y=$((Y-a3))
		a0=5
	else
		test $a0 = 5 && Y=$((Y+a2))
		Y=$((Y-a3))
		a0=4
	fi
done
: '
1262
292*4=1168
1262-1168=94
'
