#!/bin/bash
eval $(xdotool getmouselocation --shell)
xdotool keyup Return
wmctrl -a "$1"
sleep 0.3
a=$2
a1=$((a/6))
a2=0
if (( $a1 < 1 ))
then
	a1=1
fi
for((i=0;i<$a1;i++))
do
	a2=$((6))
	if (( $a < 6 ))
	then
		a2=$((a))
	fi

	for((i=0;i<$a2;i++))
	do
		xdotool mousemove --sync $X $((Y+i*240)) click 1
		sleep 0.2
	done
	xdotool key Next
	sleep 0.4
	a=$((a-6))
done
