#!/bin/bash
sleep 1
wmctrl -a "Kampen om Wesnoth"
sleep 2
f=$HOME/typestr

function mymethod
{
	xclip -i $f -selection clipboard
	xdotool key colon
	sleep 0.5
	xdotool key Ctrl+v
	sleep 0.5
	xdotool key Return
	sleep 0.5
}

#debug
echo 'unit advances=5' > $f
mymethod
sleep 8
echo 'unit experience=19999' > $f
mymethod
#xdotool type 'unit max_hitpoints=2000'
echo 'unit max_hitpoints=2000' > $f
mymethod
#echo 'unit hitpoints=2000' > $f
#mymethod
echo 'unit max_moves=40' > $f
mymethod
