#!/bin/bash
sleep 1
wmctrl -a "Kampen om Wesnoth"
sleep 2

function mymethod
{
	xclip -i $HOME/typestr -selection clipboard
	xdotool key colon
	sleep 0.2
	xdotool key Ctrl+v
	sleep 0.02
	xdotool key Return
	sleep 4
}

echo 'unit max_moves=30' > $HOME/typestr
mymethod
echo 'unit advances=5' > $HOME/typestr
mymethod
sleep 4
echo 'unit experience=9999' > $HOME/typestr
mymethod
#xdotool type 'unit max_hitpoints=500'
echo 'unit max_hitpoints=500' > $HOME/typestr
mymethod
echo 'unit hitpoints=500' > $HOME/typestr
mymethod
