#!/bin/bash
sleep 1
wmctrl -a "Kampen om Wesnoth"
sleep 2

function mymethod
{
	xclip -i $HOME/typestr -selection clipboard
	xdotool key colon
	sleep 0.2
	xdotool key Ctrl+v
	sleep 0.02
	xdotool key Return
	sleep 2
}

#debug
echo 'unit advances=5' > $HOME/typestr
mymethod
sleep 8
echo 'unit experience=19999' > $HOME/typestr
mymethod
#xdotool type 'unit max_hitpoints=2000'
echo 'unit max_hitpoints=2000' > $HOME/typestr
mymethod
#echo 'unit hitpoints=2000' > $HOME/typestr
#mymethod
echo 'unit max_moves=40' > $HOME/typestr
mymethod
