#!/bin/bash
dnf install -y dkms git kernel-devel
git clone https://github.com/cilynx/rtl88x2BU_WiFi_linux_v5.3.1_27678.20180430_COEX20180427-5959.git /usr/src/rtl88x2bu-5.3.1
dkms add -m rtl88x2bu -v 5.3.1
dkms build -m rtl88x2bu -v 5.3.1
dkms install -m rtl88x2bu -v 5.3.1
modprobe 88x2bu
