#!/bin/bash
cd "${HOME}/Git/rtl88x2bu"
VER=$(sed -n 's/\PACKAGE_VERSION="\(.*\)"/\1/p' dkms.conf)
git pull --rebase
sudo dkms build -m rtl88x2bu -v "${VER}"
sudo dkms install -m rtl88x2bu -v "${VER}"
