#!/bin/bash
function confirm {
	while true
	do
		read -r -p "Are You Sure? [Y/n] " input

		case $input in
		[yY][eE][sS]|[yY])
			return 1
			;;
		[nN][oO]|[nN])
			return 0
			;;
		*)
			echo "Invalid input..."
			;;
		esac
	done
}
