#!/bin/python3
from math import sqrt
from plumbum import local, FG, BG
import pyautogui as gui
import sys
import time

gui.PAUSE = 0.02
gui.FAILSAFE = True

gui.keyUp('enter')

wmctrl = local['wmctrl']
wmctrl['-xa', 'ck2.ck2'] & FG

time.sleep(0.1)

_next = '.'

_id = sys.argv[1]
if len(sys.argv) == 2:
	sys.argv += [0] * 5
_dip = str(100 - int(sys.argv[2]))
_mar = str(100 - int(sys.argv[3]))
_ste = str(100 - int(sys.argv[4]))
_int = str(100 - int(sys.argv[5]))
_lea = str(100 - int(sys.argv[6]))

_list = ['add_diplomacy ' + _id + ' ' + _dip]
_list += ['add_martial ' + _id + ' ' + _mar]
_list += ['add_stewardship ' + _id + ' ' + _ste]
_list += ['add_intrigue ' + _id + ' ' + _int]
_list += ['add_learning ' + _id + ' ' + _lea]
_list += ['add_artifact armor_tier_4_guardian ' + _id]
_list += ['add_artifact chinese_book_economy ' + _id]
_list += ['add_artifact chinese_dragon_amulet ' + _id]
_list += ['add_artifact heros_crown_2 ' + _id]
_list += ['add_artifact jade_dragon ' + _id]
_list += ['add_artifact jian_sword ' + _id]
_list += ['add_artifact the_bestiary ' + _id]
_list += ['add_artifact the_odyssey ' + _id]
_list += ['add_artifact treatise_on_fishing ' + _id]
_list += ['add_trait administrator ' + _id]
_list += ['add_trait adventurer ' + _id]
_list += ['add_trait architect ' + _id]
_list += ['add_trait augustus ' + _id]
_list += ['add_trait born_in_the_purple ' + _id]
_list += ['add_trait brave ' + _id]
_list += ['add_trait brilliant_strategist ' + _id]
_list += ['add_trait celibate ' + _id]
_list += ['add_trait charitable ' + _id]
_list += ['add_trait chaste ' + _id]
_list += ['add_trait content ' + _id]
_list += ['add_trait crusader_king ' + _id]
_list += ['add_trait diligent ' + _id]
_list += ['add_trait duelist ' + _id]
_list += ['add_trait fair ' + _id]
_list += ['add_trait falconer ' + _id]
_list += ['add_trait flanker ' + _id]
_list += ['add_trait gamer ' + _id]
_list += ['add_trait gardener ' + _id]
_list += ['add_trait genius ' + _id]
_list += ['add_trait gregarious ' + _id]
_list += ['add_trait groomed ' + _id]
_list += ['add_trait guilds_trait_master ' + _id]
_list += ['add_trait honest ' + _id]
_list += ['add_trait humble ' + _id]
_list += ['add_trait hunter ' + _id]
_list += ['add_trait immortal ' + _id]
_list += ['add_trait inspiring_leader ' + _id]
_list += ['add_trait just ' + _id]
_list += ['add_trait kind ' + _id]
_list += ['add_trait mystic ' + _id]
_list += ['add_trait organizer ' + _id]
_list += ['add_trait patient ' + _id]
_list += ['add_trait physician ' + _id]
_list += ['add_trait poet ' + _id]
_list += ['add_trait robust ' + _id]
_list += ['add_trait scholar ' + _id]
_list += ['add_trait shrewd ' + _id]
_list += ['add_trait siege_leader ' + _id]
_list += ['add_trait socializer ' + _id]
_list += ['add_trait strategist ' + _id]
_list += ['add_trait strong ' + _id]
_list += ['add_trait temperate ' + _id]
_list += ['add_trait theologian ' + _id]
_list += ['add_trait trusting ' + _id]
_list += ['add_trait unyielding_leader ' + _id]
_list += ['add_trait zealous ' + _id]
_list += ['add_modifier kuru_ec_bodyguard ' + _id + ' -1']
_list += ['add_modifier kuru_ec_extraordinary_builder ' + _id + ' -1']
_list += ['add_modifier kuru_ec_extraordinary_leader ' + _id + ' -1']
_list += ['add_modifier kuru_ec_extraordinary_plotter ' + _id + ' -1']
_list += ['add_modifier kuru_ec_quick_reinforcements ' + _id + ' -1']
_list += ['culture ' + _id + ' arberian']
_list += ['remove_trait misguided_warrior ' + _id]
_list += ['remove_trait skilled_tactician ' + _id]
_list += ['remove_trait tough_soldier ' + _id]
_list += ['clear']

_iter = iter(_list)

def _check():
	global _next
	_next = next(_iter, 0)
	_bool = _next != 0
	return _bool

while _check():
	gui.write(_next)
	gui.press('enter')
