#!/bin/bash
#xdotool key --clearmodifiers Alt+Tab
#wmctrl -a "$1"
sleep 0.5

function mouse
{
  xdotool mousemove --sync "$2" "$3" click 1
}

for((i=0;i<"$4";i++))
do
  sleep 0.2
  mouse 120 173
  sleep 0.2
  xdotool key a
done
