#!/bin/bash
xdotool key --clearmodifiers Alt+Tab
sleep 1
for((i=0;i<$1;i++))
do
	sleep 0.01
	xdotool mousemove --sync 308 500 mousedown 1
	sleep 0.1
	xdotool mousemove --sync 389 500
	sleep 0.01
	xdotool mousemove --sync 470 500
	sleep 0.01
	xdotool mousemove --sync 552 500 mouseup 1
	sleep 6.2
done
