#!/bin/bash
d="$HOME"/.redeclipse
mkdir -p "$d"
f1="$d"/autoexec.cfg
f2="$d"/vars.cfg

> "$f1"

function tof1
{
  echo "$1" >> "$f1"
}

tof1 'bothurtstop 1'
tof1 'botoffset 20'
tof1 'botskillmax 50'
tof1 'botskillmin 50'
tof1 'botspawndelay 63000'
tof1 'botspawndelaybomber 63000'
tof1 'botspawndelaycapture 63000'
tof1 'botspawndelaydefend 63000'
tof1 'botspawndelaygauntlet 63000'
tof1 'botspeed 20'
tof1 'botteamdamage 4'
tof1 'burndamage 40'
tof1 'burntime 10500'
tof1 'defendbuffarea 400'
tof1 'defendbuffdamage 2'
tof1 'defendbuffshield 2'
tof1 'defendregendelay 800'
tof1 'defendregenextra 4'
tof1 'dronemaxcarry 1'
tof1 'dronespeed 10'
tof1 'flamerdamage1 20'
tof1 'flamerdamage2 30'
tof1 'flamerdelayreload 90'
tof1 'flamerlaser 1'
tof1 'gravity 25'
tof1 'gruntmaxcarry 1'
tof1 'gruntspeed 10'
tof1 'jumpspeed 120.0'
tof1 'numplayers 41'
tof1 'plasmaaidist1 0'
tof1 'plasmaaidist2 0'
tof1 'plasmadamage1 0'
tof1 'plasmadamage2 0'
tof1 'plasmadisabled 1'
tof1 'playerhealth 99999999'
tof1 'playerhurtstop 1'
tof1 'playermaxcarry 7'
tof1 'playerspeed 300'
tof1 'playerteamdamage 4'
tof1 'playerweight 50.0'
tof1 'rocketammosub1 0'
tof1 'rocketammosub2 0'
tof1 'rocketlaser 1'
tof1 'turrethurtstop 1'
tof1 'turretmaxcarry 1'
tof1 'zapperaidist1 0'
tof1 'zapperaidist2 0'
tof1 'zapperdamage1 0'
tof1 'zapperdamage2 0'
tof1 'zapperdisabled 1'

cp "$f1" "$f2"
